### ISSUE TITLE
Disparity in method return

### ISSUE THREAD

**Issue by ctgraham** [ulsdevteam/primo-request-workflow#10]
https://github.com/ulsdevteam/primo-request-workflow/blob/ce1c38a23e520da7ea2f2f3050e6bb32dd944722/workflow.php#L178-L184

How will the `Location` header function here? (vs. the string return value).

**Comment by wopsononock** [comment]
I think your addition of the buildUrl method actually eliminates the need for this switch statement altogether.

**Comment by wopsononock** [comment]
Going even further, since HSLS is allowing us to route their patrons through the E-ZBorrow workflow, I don't think we even need the bookRequest method at all.

**Comment by wopsononock** [comment]
fixed in 2ad239fa071218afb85567f1e3ca3866fb327514
