### ISSUE TITLE
Can we use the Accept Content Type header to distinguish JSON requests

### ISSUE THREAD

**Issue by ctgraham** [ulsdevteam/primo-request-workflow#12]
https://github.com/ulsdevteam/primo-request-workflow/blob/ce1c38a23e520da7ea2f2f3050e6bb32dd944722/workflow.php#L306

The eliminates the need to send an additional URL parameter.

**Comment by wopsononock** [comment]
fixed in 3306d452bcce7181ac57cda7dc9abf76eb715f76
