### ISSUE TITLE
End of life for variables by name

### ISSUE THREAD

**Issue by ctgraham** [ulsdevteam/primo-request-workflow#15]
The translation of URL inputs into variables by the same name per here:
https://github.com/ulsdevteam/primo-request-workflow/blob/48270fe12301943dd4ebcc3dfe90770691f1b788/workflow.php#L27-L35

Is essentially end of life.  The only remaining instance is `$type` here:
https://github.com/ulsdevteam/primo-request-workflow/blob/48270fe12301943dd4ebcc3dfe90770691f1b788/workflow.php#L201

Replacing `$type` with `$userParams['requesttype']` would fully remove the need for lines 27 through 35.

**Comment by wopsononock** [comment]
Thanks for writing these up. I've addressed this in 54af7c6a5773cd1628606d1b47511a22af21e6f5
