### ISSUE TITLE
ILLiad check is incongruous with ILLiad redirect

### ISSUE THREAD

**Issue by ctgraham** [ulsdevteam/primo-request-workflow#16]
The ILLiad check is hardcoded against the ULS ILLiad instance:

https://github.com/ulsdevteam/primo-request-workflow/blob/48270fe12301943dd4ebcc3dfe90770691f1b788/workflow.php#L109-L116

but the ILLiad redirect is dynamic based on campus to either HSLS or ULS.

The result is that all HSLS patrons will see the interstitial page.

**Comment by wopsononock** [comment]
Good catch.  Addressed here 1efc844cf2291d13d44e067272398ad35680a2d0

**Comment by ctgraham** [comment]
`ILLIAD_API_KEY` will vary by base url now, but is left as a single constant in that commit.

**Comment by wopsononock** [comment]
Gave this another shot in 399bddeedbfde159b88af888327245ef5da165df 
Will have to remember to add the 2nd API key to our configuration

**Comment by ctgraham** [comment]
This is a good first step and covers the short-term need.
https://github.com/ulsdevteam/primo-request-workflow/blob/399bddeedbfde159b88af888327245ef5da165df/workflow.php#L131-L136

For a subsequent iteration we'll need to plan how this can be abstracted away from the code and entirely into a configuration file.  Specifically, with the ReShare-provided add-in, we'll almost certainly need to contribute back code to allow the add-in to operate against multiple ILLiad providers.  To make such a contribution generally applicable, what happens if an institution has three, or four?
