### ISSUE TITLE
Alma / ILLiad edge cases

### ISSUE THREAD

**Issue by ctgraham** [ulsdevteam/primo-request-workflow#17]
User detection is currently bound to SAML authentication:
https://github.com/ulsdevteam/primo-request-workflow/blob/48270fe12301943dd4ebcc3dfe90770691f1b788/workflow.php#L66-L73

With a lookup of that user in Alma:
https://github.com/ulsdevteam/primo-request-workflow/blob/48270fe12301943dd4ebcc3dfe90770691f1b788/workflow.php#L79-L95

Alumni and candidates and sponsored accounts can pass the SAML test, but will fail the Alma lookup (correctly).

OSHER will pass the SAML test, and will soon pass the Alma lookup, but are not permitted to use ILL.

**Comment by wopsononock** [comment]
I'm trying to think of ways to test this.  In what specific ways will OSHER people be identified?

**Comment by ctgraham** [comment]
@bdgregg is working on the OSHER patron feed with Pitt IT in Sandbox.  Currently there is at least a user statistical category:
```
<user_statistics>
<user_statistic segment_type="External">
<statistic_category>RC_OSHER</statistic_category>
<category_type>RESPONSIBILITY_CENTER</category_type>
<statistic_note>OSHER Student</statistic_note>
</user_statistic>
</user_statistics>
```
There may also be a dedicated User Group?

**Comment by wopsononock** [comment]
Something like this will probably work if we rely on the statistical categories
`<?php 
if ($user->getUserRecord($userId) && $user->getUserRecord($userId)->campus_code && $user->getUserRecord($userId)->user_statistic) {
    foreach($user->getUserRecord($userId)->user_statistic as $statistic){
        if ($statistic->statistic_category->value == 'RC_OSHER') {
            $requestStatus = "osher";
            //write a component below to display a custom error message for these folks
        }
        else{
            //continue on with the existing workflow
        }
    }
    ?>`

**Comment by wopsononock** [comment]
Turns out OSHER participants will be put into usergroup upprogram and all upprogram members are still blocked from external requests.  a766b6a996e993be7a5354a8b8a78475af20523c blocks upprogram and displays a custom message in that case. I've tested it with an OSHER participant.
