### ISSUE TITLE
return outside of function

### ISSUE THREAD

**Issue by wopsononock** [ulsdevteam/primo-request-workflow#2]
Maybe a leftover from the refactor?

https://github.com/ulsdevteam/primo-request-workflow/blob/446a1e4077e19082f30e63f399ec497ca95da19b/workflow.php#L224

**Comment by wopsononock** [comment]
I believe this needs to be inside the brace above it

**Comment by ctgraham** [comment]
Concur.  Fixed with 4d93a19 .
