### ISSUE TITLE
header set in all cases

### ISSUE THREAD

**Issue by wopsononock** [ulsdevteam/primo-request-workflow#3]
Tried adding $type==chapter or article, but not working so far.

https://github.com/ulsdevteam/primo-request-workflow/blob/446a1e4077e19082f30e63f399ec497ca95da19b/workflow.php#L273

**Comment by wopsononock** [comment]
as long as I still have access to $type, I should be able to make this work.  Was having some trouble with incoming url pages and pickup parameters not being set when I did a quick test from primo.  can probably figure that out.

**Comment by ctgraham** [comment]
Standardizing the expected responses of this script would be a good improvement here.  We have a few distinct output formats:

Raw text:
https://github.com/ulsdevteam/primo-request-workflow/blob/446a1e4077e19082f30e63f399ec497ca95da19b/workflow.php#L236

JSON:
https://github.com/ulsdevteam/primo-request-workflow/blob/446a1e4077e19082f30e63f399ec497ca95da19b/workflow.php#L252-L253

HTTP headers:
https://github.com/ulsdevteam/primo-request-workflow/blob/446a1e4077e19082f30e63f399ec497ca95da19b/workflow.php#L269-L273

Better would be to standardize to one output format (say JSON), and have the caller respond with display, redirects, etc.

**Comment by wopsononock** [comment]
Agree in the case of the raw text.  For the HTTP header set for article and chapter scan requests and for book borrowing patrons ineligible for EZ Borrow, I can't think of a reason to hit our html page first, so I'd like to link the user straight to workflow.php in those cases.

**Comment by ctgraham** [comment]
Is the javascript logic on Primo doing the work of choosing whether to direct the user directly to the PHP or to an HTML intermediary?  If so, I'd be concerned that we have three distinct layers of business logic here: the GES rules, the AngularJS, and the PHP.

**Comment by wopsononock** [comment]
Yeah.  We configure 3 separate links for book/article/chapter requests, so I can merely point at the php for two of them.
________________________________

**Comment by wopsononock** [comment]
wrapping the location header with 'if ($type=='chapter'||$type=='article'){' seems to work fine after fixing a bug in the url builder, so will close this issue.  Will continue on with the other response format improvements separately.
