### ISSUE TITLE
bookRequest returns only the query string, missing the base url

### ISSUE THREAD

**Issue by wopsononock** [ulsdevteam/primo-request-workflow#4]
Can't spot where it's getting omitted.  

https://github.com/ulsdevteam/primo-request-workflow/blob/446a1e4077e19082f30e63f399ec497ca95da19b/workflow.php#L164

**Comment by ctgraham** [comment]
Parameter is named `$campus` in the switch, `$target` in the function declaration.
https://github.com/ulsdevteam/primo-request-workflow/blob/446a1e4077e19082f30e63f399ec497ca95da19b/workflow.php#L181-L184

**Comment by wopsononock** [comment]
That worked.
