### ISSUE TITLE
AJAX vs. HTTP headers

### ISSUE THREAD

**Issue by ctgraham** [ulsdevteam/primo-request-workflow#9]
https://github.com/ulsdevteam/primo-request-workflow/blob/main/workflow.php#L255-L260

Will this `Location` header work when called via AJAX?

**Comment by wopsononock** [comment]
I rewrote this to remove HSLS (unnecessary as they can use EZB now) and send a message and ILLIAD link back to the browser in the case of UPPROGRAM.
